---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/part-of: apps
    app.kubernetes.io/component: custom
  annotations:
    storageclass.kubernetes.io/default-class: longhorn
