---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cluster-arpa
  namespace: cert-manager
spec:
  secretName: wildcard-cluster-arpa-tls
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  commonName: "*.cluster.arpa"
  dnsNames:
    - "*.cluster.arpa"
    - "cluster.arpa"
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
    group: cert-manager.io
